apiVersion: v1
kind: Service
metadata:
  name: cyclos-app-svc
  labels:
    run: cyclos-app-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 8080
    protocol: TCP
    name: http-admin
  selector:
    run: cyclos-app
